server:
  port: 9000

mybatis:
  mapper-locations: classpath:conf/mybatis/mapper/*.xml
  config-location: classpath:conf/mybatis/mybatis-configuration.xml

spring:
  rabbitmq:
    virtual-host: dc3
    host: 10.10.77.246
    port: 5672
    username: dc3
    password: dc3
  elasticsearch:
    bboss:
      icp-view:
        name: iot-es
        elasticUser:
        elasticPassword:
        elasticsearch:
          rest:
            hostNames: 10.10.77.246:19200
          dateFormat: yyyy.MM.dd HH:mm:ss
          timeZone: Asia/Shanghai
          showTemplate: true
          discoverHost: false
        dslfile:
          refreshInterval: -1
        http:
          timeoutConnection: 5000
          timeoutSocket: 5000
          connectionRequestTimeout: 5000
          retryTime: 1
          maxLineLength: -1
          maxHeaderCount: 200
          maxTotal: 400
          defaultMaxPerRoute: 200
          soReuseAddress: false
          soKeepAlive: false
          timeToLive: 3600000
          keepAlive: 3600000
          keystore:
          keyPassword:
          hostnameVerifier:
  redis:
    redisson:
      config: classpath:redisson.yml
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    read:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: ok123
      driverClassName: com.mysql.jdbc.Driver
    write:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
      username: root
      password: ok123
      driverClassName: com.mysql.jdbc.Driver
    dynamic:
      primary: write
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: api_route
          uri: http://127.0.0.1:80/
          predicates:
            - Path=/api/**
          filters:
            #            - 省略第一个路径地址api
            - StripPrefix=1
            #            - 把请求路径中的api替换成空
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#        - id: test_route
#          uri: http://127.0.0.1:9000
#          predicates:
#            - Path=/api/test/**
#          filters:
#            - RewritePath=/api/test/(?<segment>.*), /$\{segment}

mica:
  xss:
    exclude-patterns:
    enabled: true


flowable:
  #解决乱码
  activity-font-name: "宋体"
  annotation-font-name: "宋体"
  label-font-name: "宋体"